"""add labelKey and socialType to Contact

Revision ID: 6d0f1ac0c26e
Revises: 
Create Date: 2026-02-02 16:03:26.817329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d0f1ac0c26e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('labelKey', sa.String(length=255), nullable=True))
    op.add_column('contact', sa.Column('socialType', sa.String(length=50), nullable=True))
    op.alter_column('contact', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_column('contact', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('label', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('contact', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_column('contact', 'socialType')
    op.drop_column('contact', 'labelKey')
    # ### end Alembic commands ###
